# Generated by Django 5.2.9 on 2025-12-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_sale_discount_amount_sale_notes_sale_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_customers', models.IntegerField(default=0)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('avg_sale_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Statistics',
            },
        ),
    ]
